version: '2'

services:
  app:
    image: 'yandex_enrollment_another:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    ports:
        - 80:80
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/default_database
      - SPRING_DATASOURCE_USERNAME=username
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
          
  db:
    image: 'postgres:13.1-alpine'
    ports:
      - 5432:5432
    container_name: db
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=default_database